version: "3"
services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
     - ./init:/docker-entrypoint-initdb.d
    env_file:
      - ../mariadb.env
    ports:
      - 3306:3306
  api:
    image: rlkamradt/winepairingapi
    volumes:
    - ../config:/project/config
    ports:
      - 5000:5000
